spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update  # 자동으로 DDL 실행 -> 어플리케이션 실행 시 데이터 베이스 스키마가 자동으로 업데이트됨

    # 테이블 생성 후에 data.sql 실행 - 애플리케이션 시작 시점에 data.sql 파일 실행
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/on_board?useSSL=false&serverTimezone=UTC  # MySQL 서버 URL 및 데이터베이스 이름 / useSSL=false : SSL연결 사용 안함
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버
jwt:
  issuer: jsjs3489@gmail.com
  secret_key: qlalfdldi